'use client';
import {useInterface} from '../components/InterfaceLanguage';
import Link from 'next/link';
export default function Home() {
 const {ui}=useInterface();

  return <main className="page home"><section className="hero"><div><p className="eyebrow">{ui("A living connection to the archive")}</p><h1>{ui("Discover a legacy.")}{' '}<br /><em>{ui("Begin with the source.")}</em></h1><p className="intro">{ui("Explore the Dr. B. R. Ambedkar Digital Heritage Archive through preserved documents, verified text and questions grounded in evidence.")}</p><div className="button-row"><Link className="button" href="/archive">{ui("Explore the archive ↗")}</Link><Link className="text-link" href="/ai">{ui("Ask a research question →")}</Link></div><p className="subtle">{ui("An accessible reading and research space. Take your time.")}</p></div><div className="hero-art" aria-hidden="true"><div className="arch-ring"><div className="paper-lines"><span /><span /><span /><span /><span /><span /></div></div><span className="art-caption">{ui("PRESERVE / UNDERSTAND / DISCOVER")}</span></div></section>
    <section aria-labelledby="choose"><div className="section-heading"><h2 id="choose">{ui("How would you like to explore?")}</h2><span>{ui("Explore through sources.")}</span></div><div className="path-grid">
      <Link className="path-card blue" href="/ai"><span className="card-number">{ui("01 / ASK")}</span><span className="card-icon" aria-hidden="true">{ui("✳")}</span><h3>{ui("AI Research Assistant")}</h3><p>{ui("Ask a question. Follow the evidence. Read the sources behind each response.")}</p><span className="card-action">{ui("Start a conversation ↗")}</span></Link>
      <Link className="path-card" href="/archive"><span className="card-number">{ui("02 / READ")}</span><span className="card-icon" aria-hidden="true">{ui("▤")}</span><h3>{ui("The Archive")}</h3><p>{ui("Browse published records, open preserved originals and read curator-verified text.")}</p><span className="card-action">{ui("Browse documents ↗")}</span></Link>
      <Link className="path-card ochre" href="/experience"><span className="card-number">{ui("03 / EXPLORE")}</span><span className="card-icon" aria-hidden="true">{ui("◷")}</span><h3>{ui("Timeline & stories")}</h3><p>{ui("Follow curator-reviewed events, source-backed stories and learning activities.")}</p><span className="card-action">{ui("Enter the experience ↗")}</span></Link>
    <Link className="path-card" href="/speeches"><span className="card-number">{ui("04 / LISTEN")}</span><h3>{ui("Speeches & recordings")}</h3><p>{ui("Listen to published recordings and follow verified transcripts.")}</p><span className="card-action">{ui("Explore recordings ↗")}</span></Link><Link className="path-card" href="/archive?collection=manuscripts"><span className="card-number">{ui("05 / READ")}</span><h3>{ui("Manuscripts & Letters")}</h3><p>{ui("Explore approved manuscripts and correspondence. Compare reviewed text with preserved originals.")}</p><span className="card-action">{ui("Browse manuscripts & letters ↗")}</span></Link>
    <Link className="path-card" href="/archive?collection=media"><span className="card-number">{ui("06 / VIEW")}</span><h3>{ui("Media")}</h3><p>{ui("Explore approved photographs and videos, with source records and reviewed transcripts where available.")}</p><span className="card-action">{ui("Explore photographs & videos ↗")}</span></Link></div></section><aside className="trust-strip"><span className="eyebrow">{ui("A note on trust")}</span><p>{ui("Original documents and AI summaries are always distinguished. The assistant uses only verified, published archive text and says when evidence is insufficient.")}</p></aside></main>;
}
