'use client';
import {useInterface} from './InterfaceLanguage';

import Link from 'next/link';
import {FormEvent,useEffect,useRef,useState} from 'react';
type Result={status:string;message:string;warning:string;paragraphs:{text:string;evidence:{passage_id:string;quote:string}[]}[];sources:{passage_id:string;title:string;excerpt:string;reader_url:string;page_number:number|null;start_seconds:number|null;end_seconds:number|null}[]};
export default function SourceResearch({id}:{id:string}){
 const {ui}=useInterface();

 const [question,setQuestion]=useState('');const [result,setResult]=useState<Result|null>(null);const [history,setHistory]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [cloud,setCloud]=useState<boolean|null>(null);const pending=useRef<AbortController|null>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/archive/research/provider',{cache:'no-store',signal:c.signal}).then(r=>r.ok?r.json():null).then(p=>setCloud(p?.cloud??null)).catch(()=>{});return()=>{c.abort();pending.current?.abort();};},[id]);
 async function ask(text:string){
  if(busy||text.trim().length<2)return;const controller=new AbortController();pending.current=controller;setBusy(true);setError('');setResult(null);
  try{const r=await fetch('/api/archive/research/ask',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({question:text,item_id:id,history:history.slice(-4)})});if(!r.ok)throw Error('Source assistance unavailable. Please retry.');setResult(await r.json());setHistory(h=>[...h.slice(-3),text]);setQuestion('');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Source assistance unavailable');}finally{if(!controller.signal.aborted)setBusy(false);}
 }
 function submit(e:FormEvent){e.preventDefault();void ask(question);}
 return <section className="source" aria-label={ui("Source-specific AI")}><h2>{ui("AI-assisted reading")}</h2><p className="tag">{ui("AI-generated summaries and answers · verify against the source")}</p><p>{ui("Only this source’s eligible verified text can support answers. Summaries cover selected excerpts, not necessarily the whole work.")}</p><p className="subtle">{cloud===true ? ui("Questions and retrieved excerpts are sent to Google Gemini. Do not enter personal information.") : cloud===false ? ui("The configured local provider handles generation.") : ui("Provider status unavailable. Do not enter personal information; a cloud provider may be configured.")}</p><form onSubmit={submit}><label>{ui("Question about this source")}<textarea required minLength={2} maxLength={1200} value={question} onChange={e=>setQuestion(e.target.value)}/></label><div className="button-row"><button className="button" disabled={busy||question.trim().length<2}>{ui("Ask this source")}</button><button type="button" disabled={busy} onClick={()=>void ask('Summarize this source')}>{ui("Summarize verified excerpts")}</button><button type="button" disabled={busy} onClick={()=>void ask("What are the key themes and points in this source?")}>{ui("Find key points")}</button><button type="button" onClick={()=>{pending.current?.abort();setBusy(false);setResult(null);setHistory([]);setQuestion('');setError('');}}>{ui("Clear source conversation")}</button></div></form><p role="status">{busy ? ui("Checking eligible source excerpts…") : result?.message}</p>{error&&<p role="alert">{ui(error)}</p>}{result?.warning&&<p className="alert">{result.warning}</p>}{result?.paragraphs.map((p,i)=><div key={i}><p lang="en" translate="no">{p.text}</p>{p.evidence.map(e=>{const source=result.sources.find(s=>s.passage_id===e.passage_id);return source?<a key={e.passage_id} href={source.reader_url}>{ui("Supporting source: ")}{source.title}</a>:null;})}</div>)}{result?.sources.map(s=><details key={s.passage_id}><summary>{s.title} {ui(" · ")}{s.start_seconds!==null ? ui("{0}–{1} seconds", s.start_seconds, s.end_seconds) : s.page_number ? ui("Page {0}", s.page_number) : ui("Page unspecified")}</summary><blockquote lang="en" translate="no">{s.excerpt}</blockquote><a href={s.reader_url}>{ui("Navigate to cited passage")}</a></details>)}<Link className="text-link" href="/ai">{ui("Ask a broader archive question")}</Link></section>;
}

