import {expect,test,APIRequestContext} from '@playwright/test';
import fs from 'node:fs';
test.use({launchOptions:{executablePath:process.env.ARCHIVE_E2E_BROWSER}});
function credentials(){test.skip(!process.env.ARCHIVE_E2E_AUTH_FILE,'Requires isolated fixture server');const a=JSON.parse(fs.readFileSync(process.env.ARCHIVE_E2E_AUTH_FILE!,'utf8'));return {Authorization:`Basic ${Buffer.from(`${a.login}:${a.password}`).toString('base64')}`};}
function metadata(title:string,type:string,filename:string){return {title,material_type:type,original_filename:filename,source_name:'Self-created test fixture',source_locator:'https://example.invalid/local-test',source_record_locator:'https://example.invalid/local-test/item',rights_statement:'Self-created isolated test asset; permitted for automated testing. Not historical content.',provenance_confirmed:true,language:'en',description:'SYNTHETIC LOCAL TEST ONLY',access_level:'public'};}
async function transition(request:APIRequestContext,id:string,headers:Record<string,string>,action:string){const r=await request.post(`/api/archive/staff/documents/${id}/transition`,{headers,data:{action,metadata_reviewed:action==='verify'}});expect(r.status(),await r.text()).toBe(200);}
test('public photograph uses derivative and respects verification, publication and withdrawal',async({page,request})=>{
 const headers=credentials();
 // Self-created 1x1 PNG; no third-party or historical content.
 const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
 const title=`SYNTHETIC permission test ${Date.now()}`;
 const r=await request.post(`/api/archive/staff/documents?metadata=${encodeURIComponent(JSON.stringify(metadata(title,'photograph','test.png')))}`,{headers:{...headers,'Content-Type':'image/png'},data:bytes});expect(r.status(),await r.text()).toBe(201);const id=(await r.json()).id;
 await transition(request,id,headers,'verify');expect((await request.get(`/api/archive/documents/${id}/thumbnail`)).status()).toBe(404);
 await transition(request,id,headers,'publish');await page.goto(`/archive/${id}`);await expect(page.getByRole('heading',{name:title})).toBeVisible();const image=page.locator('.photo-detail img');await expect.poll(()=>image.evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
 expect(Buffer.compare(await(await request.get(`/api/archive/documents/${id}/original`)).body(),bytes)).toBe(0);
 await transition(request,id,headers,'withdraw');expect((await request.get(`/api/archive/documents/${id}/thumbnail`)).status()).toBe(404);
});
test('source-backed quiz to validated certificate and voluntary leaderboard',async({page,request})=>{
 test.setTimeout(90000);
 const headers=credentials();const title=`SYNTHETIC quiz source ${Date.now()}`;const text='SYNTHETIC TEST ONLY. Synthetic reading rooms have blue chairs.';
 const upload=await request.post(`/api/archive/staff/documents?metadata=${encodeURIComponent(JSON.stringify(metadata(title,'document','test.txt')))}`,{headers:{...headers,'Content-Type':'text/plain'},data:text});expect(upload.status()).toBe(201);const id=(await upload.json()).id;const base=`/api/archive/staff/documents/${id}`;
 expect((await request.post(`${base}/processing`,{headers,data:{}})).status()).toBe(202);
 await expect.poll(async()=>{const r=await request.get(`${base}/text`,{headers});return r.ok()?(await r.json()).snapshot?.status:'';},{timeout:60000}).toBe('extracted');
 const extracted=await(await request.get(`${base}/text`,{headers})).json();
 expect((await request.post(`${base}/text/revisions`,{headers,data:{base_revision:1,pages:extracted.segments.map((p:{sequence:number;text:string})=>({sequence:p.sequence,text:p.text})),note:'Synthetic source reviewed'}})).status()).toBe(201);
 expect((await request.post(`${base}/text/verify`,{headers,data:{revision:2,original_compared:true}})).status()).toBe(200);await transition(request,id,headers,'verify');await transition(request,id,headers,'publish');
 const quizTitle=`SYNTHETIC learning ${Date.now()}`;const draft=await request.post('/api/archive/staff/learning',{headers,data:{kind:'quiz',title:quizTitle,description:'Synthetic test activity, not historical content.',topic:'Local test',sources:[{item_id:id,revision:2,quote:'Synthetic reading rooms have blue chairs.'}],questions:[{prompt:'What color are the synthetic chairs?',options:['Blue','Green'],correct:0,explanation:'The synthetic source says blue chairs.',source_index:0}]}});expect(draft.status(),await draft.text()).toBe(201);const quiz=(await draft.json()).id;
 for(const action of ['verify','publish']){const r=await request.post(`/api/archive/staff/learning/${quiz}/transition`,{headers,data:{action,evidence_reviewed:true}});expect(r.status(),await r.text()).toBe(200);}
 for(const kind of ['timeline','story']) {
  const activityTitle=`SYNTHETIC ${kind} ${Date.now()}`;
  const created=await request.post('/api/archive/staff/learning',{headers,data:{kind,title:activityTitle,description:'SYNTHETIC TEST ONLY. A reading room.\n\nSynthetic second section.',topic:'Local test',date_label:kind==='timeline'?'2026':'',sources:[{item_id:id,revision:2,quote:'Synthetic reading rooms have blue chairs.'}]}});expect(created.status()).toBe(201);const activity=(await created.json()).id;
  expect((await(await request.get(`/api/archive/learning?kind=${kind}`)).json()).some((r:{id:string})=>r.id===activity)).toBe(false);
  for(const action of ['verify','publish'])expect((await request.post(`/api/archive/staff/learning/${activity}/transition`,{headers,data:{action,evidence_reviewed:true}})).status()).toBe(200);
  await page.goto('/experience');await page.locator('.exhibition-plaque').filter({hasText:'Local test'}).click();const card=page.locator('.exhibit-entry').filter({hasText:activityTitle});await expect(card).toBeVisible();await card.locator('summary').click();await expect(card.getByRole('link',{name:`${title} →`})).toHaveAttribute('href',`/archive/${id}?revision=2`);if(kind==='story')await expect(card.getByText('Synthetic second section.',{exact:true})).toBeVisible();
 }
 await page.goto('/experience');await page.locator('.exhibition-plaque').filter({hasText:'Local test'}).click();await page.locator('.exhibit-entry').filter({hasText:quizTitle}).getByRole('link',{name:/Begin quiz/}).click();await page.getByRole('button',{name:'Start reviewed quiz'}).click();await page.getByRole('radio',{name:'Blue',exact:true}).check();await page.getByRole('button',{name:'Submit answers'}).click();await expect(page.getByRole('heading',{name:'Completed · 1 / 1'})).toBeVisible();
 await page.getByRole('button',{name:'Create completion certificate'}).click();await page.getByRole('checkbox',{name:/Optionally share my score/}).check();await page.getByRole('button',{name:'Share score voluntarily'}).click();await expect(page.getByRole('main').getByRole('status')).toContainText('Shared as Reader-');await page.getByRole('link',{name:'View and download certificate →'}).click();await expect(page.getByRole('heading',{name:'Certificate of Completion'})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download printable certificate'}).click();expect((await download).suggestedFilename()).toBe('certificate-of-completion.html');
 const certificateUrl=page.url();await page.goto(`/quiz/${quiz}`);await page.getByRole('button',{name:'Start reviewed quiz'}).click();await page.getByRole('radio',{name:'Green',exact:true}).check();await page.getByRole('button',{name:'Submit answers'}).click();await expect(page.getByRole('heading',{name:'Completed · 0 / 1'})).toBeVisible();await page.getByRole('button',{name:'Start a new attempt'}).click();await expect(page.getByRole('button',{name:'Start reviewed quiz'})).toBeVisible();await page.goto('/experience');await expect(page.getByRole('heading',{name:'Explore the legacy'})).toBeVisible();await page.getByRole('button',{name:'Knowledge map',exact:true}).click();await expect(page.getByRole('region',{name:'Knowledge map'})).toContainText(quizTitle);await transition(request,id,headers,'withdraw');await page.reload();await page.getByRole('button',{name:'Knowledge map',exact:true}).click();await expect(page.getByRole('region',{name:'Knowledge map'})).not.toContainText(quizTitle);await page.goto(certificateUrl);await expect(page.getByRole('main').getByRole('status')).toContainText('no longer approved');
});
test('native recording playback, duration and verified transcript navigation',async({page,request})=>{
 const headers=credentials();const bytes=Buffer.alloc(44+16000);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(8000,24);bytes.writeUInt32LE(16000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(16000,40);
 const title=`SYNTHETIC silence ${Date.now()}`;const r=await request.post(`/api/archive/staff/documents?metadata=${encodeURIComponent(JSON.stringify(metadata(title,'speech','silence.wav')))}`,{headers:{...headers,'Content-Type':'audio/wav'},data:bytes});expect(r.status(),await r.text()).toBe(201);const id=(await r.json()).id;const base=`/api/archive/staff/documents/${id}`;
 const auth=JSON.parse(fs.readFileSync(process.env.ARCHIVE_E2E_AUTH_FILE!,'utf8'));await page.goto('/staff');await page.getByLabel('Staff login').fill(auth.login);await page.getByLabel('Password',{exact:true}).fill(auth.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();const staffCard=page.getByRole('article').filter({hasText:title});await staffCard.getByText('Review recording and transcript',{exact:true}).click();await staffCard.getByRole('button',{name:'Load recording and current transcript'}).click();await expect.poll(()=>staffCard.locator('audio').evaluate(e=>(e as HTMLMediaElement).duration)).toBe(1);await staffCard.locator('audio').evaluate(e=>{(e as HTMLMediaElement).muted=true;return (e as HTMLMediaElement).play();});await expect.poll(()=>staffCard.locator('audio').evaluate(e=>(e as HTMLMediaElement).currentTime)).toBeGreaterThan(0);expect((await request.get(`/api/archive/documents/${id}/playback`)).status()).toBe(404);await staffCard.getByText('Review recording and transcript',{exact:true}).click();await expect.poll(async()=>(await request.get(`${base}/playback`)).status()).toBe(401);await staffCard.getByText('Review recording and transcript',{exact:true}).click();await staffCard.getByRole('button',{name:'Load recording and current transcript'}).click();await expect.poll(()=>staffCard.locator('audio').evaluate(e=>(e as HTMLMediaElement).duration)).toBe(1);await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect.poll(async()=>(await request.get(`${base}/playback`)).status()).toBe(401);
 expect((await request.post(`${base}/recording`,{headers,data:{cues:[{start:0,end:1,text:'[Synthetic silence; not historical audio]'}]}})).status()).toBe(200);expect((await request.post(`${base}/recording/verify`,{headers,data:{revision:1,compared_with_recording:true}})).status()).toBe(200);await transition(request,id,headers,'verify');await transition(request,id,headers,'publish');
 await page.goto('/speeches');await page.getByLabel('Find a recording').fill(title);const card=page.locator('article').filter({hasText:title});await expect.poll(()=>card.locator('audio').evaluate(e=>(e as HTMLAudioElement).duration)).toBe(1);await card.getByLabel('Playback speed').selectOption('1.5');expect(await card.locator('audio').evaluate(e=>(e as HTMLAudioElement).playbackRate)).toBe(1.5);await card.getByRole('button',{name:'Play from 0.0 seconds'}).click();await expect.poll(()=>card.locator('audio').evaluate(e=>(e as HTMLAudioElement).currentTime)).toBeGreaterThan(0);
 await expect.poll(async()=>{const response=await request.post('/api/archive/research/ask',{data:{question:'Synthetic silence',material_type:'speech'}});const result=await response.json();return result.sources?.some((source:{item_id:string;start_seconds:number;end_seconds:number})=>source.item_id===id&&source.start_seconds===0&&source.end_seconds===1);},{timeout:30000}).toBe(true);
 await page.goto(`/archive/${id}?revision=1#page-1`);await expect(page.getByRole('heading',{name:'0–1 seconds',exact:true})).toBeVisible();await page.locator('audio').evaluate(e=>{const a=e as HTMLMediaElement;a.pause();a.currentTime=0.25;});await expect(page.locator('.transcript-cue')).toHaveAttribute('data-active','true');
 await transition(request,id,headers,'withdraw');expect((await request.get(`/api/archive/documents/${id}/playback`)).status()).toBe(404);
});



